runtime: python
env: flex

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

runtime_config:
  python_version: 3.13

env_variables:
  AGENT_RESOURCE_ID: "1265828154639908864"
  GOOGLE_CLOUD_LOCATION: "us-east4"
  GOOGLE_CLOUD_PROJECT: "gen-ai-hackathon-471718"
  GOOGLE_CLOUD_STAGING_BUCKET: "gs://staging-123456789"
  BUCKET_NAME: 'healthcare-rag-bucket'
  SERVICE_ACCOUNT_FILE: 'C:/Users/Piyush/Downloads/gen-ai-hackathon-471718-b72da0ad4da6.json'


automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
